# Generated by Django 3.0.3 on 2020-02-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200221_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticles',
            old_name='autho',
            new_name='author',
        ),
    ]
